# Build the Database

In [1]:
# Import dependencies
import sqlalchemy
from sqlalchemy import create_engine, inspect

import os
import pandas as pd
from tqdm import tqdm

In [2]:
# Create the engine
engine = create_engine("sqlite:///voice.sqlite")

In [3]:
# Define the file path
file_path = "../resources/clean_data/"

# Get all subdirectories
subdir = os.listdir(file_path)

# Create a dictionary to hold each df
dataframes = dict()

# Get all files in the directory
for dir in subdir:
    
    # Check only subdirectories
    if dir != '.DS_Store':

        # Define the subdirectory path
        subdir_path = file_path + dir

        # List the files in the subdirectory
        files = os.listdir(subdir_path)

        # Loop through all the files
        for file in files:
            
            # Return CSV files only
            if file.endswith(".csv"):

                # Get the file name
                filename = file.split(".")[0]

                # Dataframe name
                df_name = f'{filename}_df'

                # Create a dataframe and add to dictionary
                dataframes[df_name] = pd.read_csv(f'{subdir_path}/{file}')

# Display one dataframe
dataframes['habits_df'].head()

,id,alcohol_consumption,alcohol_pd,smoker,cigarettes_pd,carbonated_beverages,carbonated_pd,chocolate,chocolate_grams_pd,coffee,coffee_pd,citrus_fruits,citrus_fruits_pd,soft_cheese,soft_cheese_pd,tomatoes,water_litres_pd
0,voice100,casual,0.36,no,0,almost always,3.00,sometimes,30,always,3,never,0.00,almost always,100,never,1.5
1,voice101,nondrinker,0.00,no,0,almost always,3.00,sometimes,30,always,4,never,0.00,sometimes,100,sometimes,1.5
2,voice192,nondrinker,0.00,no,0,never,0.00,always,14,always,3,almost always,1.17,sometimes,100,sometimes,2.5
3,voice193,casual,0.36,yes,15,sometimes,0.61,sometimes,30,always,2,sometimes,1.00,sometimes,100,sometimes,1.0
4,voice008,casual,0.36,no,0,almost never,0.09,almost always,20,always,2,almost always,1.00,sometimes,100,almost always,1.0

In [4]:
# Write the dataframes to the database
for key, value in tqdm(dataframes.items(), "Writing to database"):
    
    # Define the table name
    table_name = key.split("_")[0]
    
    # Use to_sql()
    value.to_sql(
        table_name,
        con = engine,
        if_exists = "replace",
        index = False
    )

Writing to database: 100%|██████████████████████| 79/79 [00:23<00:00,  3.38it/s]

In [5]:
# View all of the classes
inspector = inspect(engine)
inspector.get_table_names()

['alexaval',
 'alexbval',
 'alexgval',
 'alexrval',
 'aval',
 'bval',
 'chroma1',
 'chroma10',
 'chroma11',
 'chroma12',
 'chroma2',
 'chroma3',
 'chroma4',
 'chroma5',
 'chroma6',
 'chroma7',
 'chroma8',
 'chroma9',
 'chromastd',
 'deltachroma1',
 'deltachroma10',
 'deltachroma11',
 'deltachroma12',
 'deltachroma2',
 'deltachroma3',
 'deltachroma4',
 'deltachroma5',
 'deltachroma6',
 'deltachroma7',
 'deltachroma8',
 'deltachroma9',
 'deltachromastd',
 'deltaenergy',
 'deltaenergyentropy',
 'deltamfcc1',
 'deltamfcc10',
 'deltamfcc11',
 'deltamfcc12',
 'deltamfcc13',
 'deltamfcc2',
 'deltamfcc3',
 'deltamfcc4',
 'deltamfcc5',
 'deltamfcc6',
 'deltamfcc7',
 'deltamfcc8',
 'deltamfcc9',
 'deltaspectralcentroid',
 'deltaspectralentropy',
 'deltaspectralflux',
 'deltaspectralrolloff',
 'deltaspectralspread',
 'deltazcr',
 'demographic',
 'diagnosis',
 'energy',
 'energyentropy',
 'gval',
 'habits',
 'mfcc1',
 'mfcc10',
 'mfcc11',
 'mfcc12',
 'mfcc13',
 'mfcc2',
 'mfcc3',
 'mfcc4',
 'mfcc5',
 'mfcc6',
 'mfcc7',
 'mfcc8',
 'mfcc9',
 'rval',
 'spectralcentroid',
 'spectralentropy',
 'spectralflux',
 'spectralrolloff',
 'spectralspread',
 'zcr']